ghribi_api:
    resource: "@GhribiApiBundle/Controller/"
    type:     annotation
    prefix:   /

# Vendor
fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
