services:

    access_control_allow_listener:
        class:  Ghribi\ApiBundle\Listener\AccessControlAllowListener
        tags:
          - { name: kernel.event_listener, event: kernel.response }

    http_options_listener:
        class:  Ghribi\ApiBundle\Listener\HttpOptionsListener
        tags:
          - { name: kernel.event_listener, event: kernel.request }

    letter_field_updater.service:
        class: Ghribi\ApiBundle\Services\LetterFieldService

    letter_field_updater.listener:
        class: Ghribi\ApiBundle\Listener\LetterFieldListener
        arguments: [@letter_field_updater.service]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    sonata.admin.letter:
        class: Ghribi\ApiBundle\Admin\LetterAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Letters", label: "Letter" }
        arguments:
            - ~
            - Ghribi\ApiBundle\Entity\Letter
            - ~

    sonata.admin.letter_field:
        class: Ghribi\ApiBundle\Admin\LetterFieldAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Letters", label: "Field" }
        arguments:
            - ~
            - Ghribi\ApiBundle\Entity\LetterField
            - ~
